#!/usr/bin/env bash
# GameSphere mic → PC: install / show PipeWire VBAN receiver defaults.
# Does not touch GameSphere iOS; host-side only.
set -euo pipefail

STREAM_NAME="${GAMESPHERE_VBAN_STREAM:-GameSphere}"
PORT="${GAMESPHERE_VBAN_PORT:-6980}"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pipewire/pipewire.conf.d"
CONF_FILE="$CONF_DIR/50-gamesphere-vban-recv.conf"
ACTION="${1:-install}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [install|status|uninstall|info]

  install    Write PipeWire VBAN recv config (stream=$STREAM_NAME, port=$PORT) and reload
  status     Show config path + whether PipeWire VBAN module is present
  uninstall  Remove the GameSphere PipeWire drop-in
  info       Print LAN IPs and GameSphere mic defaults (no changes)

Env overrides: GAMESPHERE_VBAN_STREAM, GAMESPHERE_VBAN_PORT
Docs: docs/MIC-TO-PC.md
EOF
}

lan_ips() {
  if command -v ip >/dev/null 2>&1; then
    ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | sort -u
  elif command -v hostname >/dev/null 2>&1 && hostname -I >/dev/null 2>&1; then
    hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | grep -v '^127\.' || true
  elif command -v ifconfig >/dev/null 2>&1; then
    # macOS / BSD fallback (info-only; PipeWire install is Linux)
    ifconfig 2>/dev/null | awk '/inet / && $2 !~ /^127\./ { print $2 }' | sort -u
  fi
}

print_card() {
  echo ""
  echo "=== GameSphere Mic to PC ==="
  echo "Stream name : $STREAM_NAME"
  echo "UDP port    : $PORT"
  echo "LAN IP(s)   :"
  local any=0
  while IFS= read -r ip; do
    [[ -z "$ip" ]] && continue
    echo "  $ip"
    any=1
  done < <(lan_ips)
  if [[ "$any" -eq 0 ]]; then
    echo "  (none detected — check Wi‑Fi/Ethernet)"
  fi
  echo ""
  echo "In GameSphere: Settings → Send mic to PC → enter a LAN IP above,"
  echo "port $PORT, stream name $STREAM_NAME. Then use the Mic chip while streaming."
  echo "Allow UDP $PORT inbound if you use a firewall."
  echo ""
}

module_present() {
  # Best-effort: module file or pw-cli / pipewire package layout
  if [[ -e /usr/lib64/pipewire-0.3/libpipewire-module-vban-recv.so ]] \
    || [[ -e /usr/lib/pipewire-0.3/libpipewire-module-vban-recv.so ]] \
    || ls /usr/lib*/pipewire-*/libpipewire-module-vban-recv.so >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

write_conf() {
  mkdir -p "$CONF_DIR"
  cat >"$CONF_FILE" <<EOF
# Generated by gamesphere-vban-setup.sh — GameSphere phone mic (VBAN)
# Stream: $STREAM_NAME  Port: $PORT  Bind: all interfaces
context.modules = [
  { name = libpipewire-module-vban-recv
    args = {
      source.ip = "0.0.0.0"
      source.port = $PORT
      sess.latency.msec = 100
      stream.props = {
        media.class = "Audio/Source"
        node.name = "gamesphere-vban"
        node.description = "GameSphere Mic (VBAN)"
      }
      stream.rules = [
        { matches = [
            { sess.name = "$STREAM_NAME" }
          ]
          actions = {
            create-stream = {
              stream.props = {
                media.class = "Audio/Source"
                node.name = "gamesphere-vban"
                node.description = "GameSphere Mic (VBAN)"
              }
            }
          }
        }
      ]
    }
  }
]
EOF
  echo "==> Wrote $CONF_FILE"
}

reload_pipewire() {
  if systemctl --user is-active --quiet pipewire.service 2>/dev/null; then
    systemctl --user try-restart pipewire.service pipewire-pulse.service wireplumber.service 2>/dev/null \
      || systemctl --user restart pipewire.service 2>/dev/null \
      || true
    echo "==> Restarted PipeWire user services (best-effort)"
  else
    echo "==> PipeWire user service not active — log out/in or run: systemctl --user restart pipewire"
  fi
}

case "$ACTION" in
  -h|--help|help)
    usage
    exit 0
    ;;
  info)
    print_card
    exit 0
    ;;
  status)
    print_card
    if [[ -f "$CONF_FILE" ]]; then
      echo "Config: present ($CONF_FILE)"
    else
      echo "Config: missing (run: $(basename "$0") install)"
    fi
    if module_present; then
      echo "PipeWire module: libpipewire-module-vban-recv found"
    else
      echo "PipeWire module: not found in usual paths — update PipeWire or use Import Tool on Windows (VB-CABLE)"
    fi
    exit 0
    ;;
  uninstall)
    if [[ -f "$CONF_FILE" ]]; then
      rm -f "$CONF_FILE"
      echo "==> Removed $CONF_FILE"
      reload_pipewire
    else
      echo "==> Nothing to remove"
    fi
    exit 0
    ;;
  install)
    if ! module_present; then
      echo "Warning: libpipewire-module-vban-recv not found in usual library paths."
      echo "Bazzite / recent Fedora usually ship it with PipeWire. Continuing anyway."
    fi
    write_conf
    reload_pipewire
    print_card
    echo "Done. Pick \"GameSphere Mic (VBAN)\" (or similar) as the recording device on the host."
    exit 0
    ;;
  *)
    echo "Unknown action: $ACTION" >&2
    usage >&2
    exit 1
    ;;
esac
